package Model;
// Generated 12-mar-2022 0:40:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Clients generated by hbm2java
 */
public class Clients  implements java.io.Serializable {


     private int nif;
     private String pic;
     private Date regDate;
     private String dir;
     private String pw;

    public Clients() {
    }

	
    public Clients(int nif, Date regDate, String dir, String pw) {
        this.nif = nif;
        this.regDate = regDate;
        this.dir = dir;
        this.pw = pw;
    }
    public Clients(int nif, String pic, Date regDate, String dir, String pw) {
       this.nif = nif;
       this.pic = pic;
       this.regDate = regDate;
       this.dir = dir;
       this.pw = pw;
    }
   
    public int getNif() {
        return this.nif;
    }
    
    public void setNif(int nif) {
        this.nif = nif;
    }
    public String getPic() {
        return this.pic;
    }
    
    public void setPic(String pic) {
        this.pic = pic;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public String getDir() {
        return this.dir;
    }
    
    public void setDir(String dir) {
        this.dir = dir;
    }
    public String getPw() {
        return this.pw;
    }
    
    public void setPw(String pw) {
        this.pw = pw;
    }




}


