package Model;
// Generated 12-mar-2022 0:40:59 by Hibernate Tools 4.3.1



/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private int delCod;
     private String company;
     private String delName;
     private String pw;

    public Delivery() {
    }

	
    public Delivery(int delCod, String pw) {
        this.delCod = delCod;
        this.pw = pw;
    }
    public Delivery(int delCod, String company, String delName, String pw) {
       this.delCod = delCod;
       this.company = company;
       this.delName = delName;
       this.pw = pw;
    }
   
    public int getDelCod() {
        return this.delCod;
    }
    
    public void setDelCod(int delCod) {
        this.delCod = delCod;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getDelName() {
        return this.delName;
    }
    
    public void setDelName(String delName) {
        this.delName = delName;
    }
    public String getPw() {
        return this.pw;
    }
    
    public void setPw(String pw) {
        this.pw = pw;
    }




}


