package Model;
// Generated 12-mar-2022 0:40:59 by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int loc;
     private int nifCli;
     private float price;

    public Orders() {
    }

    public Orders(int loc, int nifCli, float price) {
       this.loc = loc;
       this.nifCli = nifCli;
       this.price = price;
    }
   
    public int getLoc() {
        return this.loc;
    }
    
    public void setLoc(int loc) {
        this.loc = loc;
    }
    public int getNifCli() {
        return this.nifCli;
    }
    
    public void setNifCli(int nifCli) {
        this.nifCli = nifCli;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }




}


