package Model;
// Generated 12-mar-2022 0:40:59 by Hibernate Tools 4.3.1



/**
 * Shops generated by hbm2java
 */
public class Shops  implements java.io.Serializable {


     private ShopsId id;
     private String shopName;
     private Float delCosts;

    public Shops() {
    }

	
    public Shops(ShopsId id, String shopName) {
        this.id = id;
        this.shopName = shopName;
    }
    public Shops(ShopsId id, String shopName, Float delCosts) {
       this.id = id;
       this.shopName = shopName;
       this.delCosts = delCosts;
    }
   
    public ShopsId getId() {
        return this.id;
    }
    
    public void setId(ShopsId id) {
        this.id = id;
    }
    public String getShopName() {
        return this.shopName;
    }
    
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }
    public Float getDelCosts() {
        return this.delCosts;
    }
    
    public void setDelCosts(Float delCosts) {
        this.delCosts = delCosts;
    }




}


