package Model;
// Generated 12-mar-2022 0:40:59 by Hibernate Tools 4.3.1



/**
 * ShopsId generated by hbm2java
 */
public class ShopsId  implements java.io.Serializable {


     private int loc;
     private int delCod;
     private int orderDeliveryCode;

    public ShopsId() {
    }

    public ShopsId(int loc, int delCod, int orderDeliveryCode) {
       this.loc = loc;
       this.delCod = delCod;
       this.orderDeliveryCode = orderDeliveryCode;
    }
   
    public int getLoc() {
        return this.loc;
    }
    
    public void setLoc(int loc) {
        this.loc = loc;
    }
    public int getDelCod() {
        return this.delCod;
    }
    
    public void setDelCod(int delCod) {
        this.delCod = delCod;
    }
    public int getOrderDeliveryCode() {
        return this.orderDeliveryCode;
    }
    
    public void setOrderDeliveryCode(int orderDeliveryCode) {
        this.orderDeliveryCode = orderDeliveryCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ShopsId) ) return false;
		 ShopsId castOther = ( ShopsId ) other; 
         
		 return (this.getLoc()==castOther.getLoc())
 && (this.getDelCod()==castOther.getDelCod())
 && (this.getOrderDeliveryCode()==castOther.getOrderDeliveryCode());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLoc();
         result = 37 * result + this.getDelCod();
         result = 37 * result + this.getOrderDeliveryCode();
         return result;
   }   


}


