package View;

import Controller.EmpleadoManager;
import Model.*;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

public class Empleados extends javax.swing.JPanel {

    private static Empleados empleadosPane = new Empleados();
    private static DefaultListModel<String> model;

    /**
     * Creates new form Orders
     */
    public Empleados() {
        initComponents();
    }

    public static Empleados getPane() {
        return empleadosPane;
    }

    public static void init() {
        // Inicializa el ResultSet de EmpleadoManager
        EmpleadoManager.start();
        empleadosPane.toggleBackward(false);
        empleadosPane.toggleForward(true);
        empleadosPane.showEmpleado(EmpleadoManager.next());
        empleadosPane.updateUI();
    }

    private void showEmpleado(Empleado e) {
        // Muestra los datos del empleado indicado
        this.numeroEmp.setText(String.valueOf(e.getNumero()));
        this.nombreEmp.setText(e.getNombre());
        this.apellidosEmp.setText(e.getApellido());
        this.sueldoBase.setText(String.valueOf(e.getSueldoBase()));
        this.sueldoExtra.setText(String.valueOf(e.getSueldoExtra()));
        this.sueldoReal.setText(String.valueOf(e.getSueldoReal()));
        this.sueldoMax.setText("(max." + String.valueOf(e.getSueldoMaximo()) + ")");
        this.image.setIcon(new ImageIcon("./src/Data/fotos/" + e.getFoto() ));
    }

    private void updateList(Empleado e) {
        // Actualiza los datos del JList con trabajos referentes al empleado
        // actual.
        model = new DefaultListModel<>();

        // Obtener los trabajos para la lista
        EmpleadoManager.getTrabajos(e.getNumero()).forEach(t -> {
            model.addElement(t.toString());
        });

        trabajosList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empleadosTitle = new javax.swing.JLabel();
        numeroEmpLabel = new javax.swing.JLabel();
        numeroEmp = new javax.swing.JLabel();
        nombreEmpLabel = new javax.swing.JLabel();
        nombreEmp = new javax.swing.JLabel();
        sueldosLabel = new javax.swing.JLabel();
        sueldoBase = new javax.swing.JLabel();
        firstButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        trabajosList = new javax.swing.JList<>();
        trabajosTitle = new javax.swing.JLabel();
        sueldoBaseLabel = new javax.swing.JLabel();
        sueldoExtra = new javax.swing.JLabel();
        apellidosEmpLabel = new javax.swing.JLabel();
        apellidosEmp = new javax.swing.JLabel();
        sueldoExtraLabel = new javax.swing.JLabel();
        sueldoRealLabel = new javax.swing.JLabel();
        sueldoReal = new javax.swing.JLabel();
        calcularSueldoReal = new javax.swing.JButton();
        calcularSueldoExtra = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        verTrabajos = new javax.swing.JButton();
        sueldoMax = new javax.swing.JLabel();

        empleadosTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        empleadosTitle.setText("Empleados");

        numeroEmpLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numeroEmpLabel.setText("Número");

        numeroEmp.setText("numero");

        nombreEmpLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreEmpLabel.setText("Nombre");

        nombreEmp.setText("nombre");

        sueldosLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sueldosLabel.setText("Sueldos");

        sueldoBase.setText("sueldoBase");

        firstButton.setText("Primero");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        prevButton.setText("Anterior");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Siguiente");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setText("Útlimo");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        trabajosList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trabajosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane.setViewportView(trabajosList);

        trabajosTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        trabajosTitle.setText("Trabajos");

        sueldoBaseLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sueldoBaseLabel.setText("Base");

        sueldoExtra.setText("sueldoExtra");

        apellidosEmpLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        apellidosEmpLabel.setText("Apellidos");

        apellidosEmp.setText("apellidos");

        sueldoExtraLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sueldoExtraLabel.setText("Extra");

        sueldoRealLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sueldoRealLabel.setText("Real");

        sueldoReal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        sueldoReal.setText("sueldoReal");

        calcularSueldoReal.setText("Calcular Sueldo Real");
        calcularSueldoReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularSueldoRealActionPerformed(evt);
            }
        });

        calcularSueldoExtra.setText("Calcular Sueldo Extra");
        calcularSueldoExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularSueldoExtraActionPerformed(evt);
            }
        });

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setText("Image");
        image.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        verTrabajos.setText("Ver historial de trabajos");
        verTrabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTrabajosActionPerformed(evt);
            }
        });

        sueldoMax.setText("sueldoMax");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(empleadosTitle)
                        .addGap(401, 401, 401)
                        .addComponent(trabajosTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nombreEmpLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(apellidosEmpLabel)
                                                    .addComponent(apellidosEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(numeroEmpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstButton)
                                            .addComponent(prevButton))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nextButton)
                                            .addComponent(lastButton))))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calcularSueldoReal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(sueldoExtraLabel)
                                                .addComponent(sueldoBaseLabel)
                                                .addComponent(sueldoRealLabel))
                                            .addComponent(sueldosLabel))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sueldoExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sueldoReal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sueldoMax)))
                                    .addComponent(calcularSueldoExtra)
                                    .addComponent(verTrabajos)))
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trabajosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numeroEmpLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroEmp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nombreEmpLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreEmp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(apellidosEmpLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(apellidosEmp))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sueldosLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sueldoBaseLabel)
                                    .addComponent(sueldoBase))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sueldoExtraLabel)
                                    .addComponent(sueldoExtra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sueldoRealLabel)
                                    .addComponent(sueldoReal))))
                        .addGap(1, 1, 1)
                        .addComponent(sueldoMax)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(prevButton)
                                .addComponent(nextButton))
                            .addComponent(calcularSueldoExtra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(firstButton)
                                .addComponent(calcularSueldoReal))
                            .addComponent(lastButton)))
                    .addComponent(jScrollPane))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Event Listeners y recorrido de empleados">
    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        // Muestra el primer empleado
        showEmpleado(EmpleadoManager.first());

        // Estamos en el primero > No podemos retroceder
        toggleBackward(false);

        // Ya se puede avanzar si antes no se podía
        if (!nextButton.isEnabled())
            toggleForward(true);
    }//GEN-LAST:event_firstButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        // Muestra el último empleado
        showEmpleado(EmpleadoManager.last());

        // Estamos en el último > No podemos avanzar
        toggleForward(false);

        // Ya se puede retroceder si antes no se podía
        if (!prevButton.isEnabled())
            toggleBackward(true);
    }//GEN-LAST:event_lastButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // Muestra el empleado anterior
        showEmpleado(EmpleadoManager.prev());

        // Si hemos llegado al principio > No podemos retroceder
        if (EmpleadoManager.isFirst()) {
            toggleBackward(false);
        }

        // Si antes no podíamos avanzar, ahora ya sí
        if (!nextButton.isEnabled())
            toggleForward(true);
    }//GEN-LAST:event_prevButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // Muestra el empleado siguiente
        showEmpleado(EmpleadoManager.next());

        // Si hemos llegado al final, no podemos avanzar
        if (EmpleadoManager.isLast()) {
            toggleForward(false);
        }

        // Si antes no podíamos retroceder, ahora ya sí
        if (!prevButton.isEnabled())
            toggleBackward(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void verTrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTrabajosActionPerformed
        // Mostramos todos los trabajos del empleado
        updateList(EmpleadoManager.get());
    }//GEN-LAST:event_verTrabajosActionPerformed

    private void calcularSueldoExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularSueldoExtraActionPerformed
        // Calcular el sueldo extra
        float sExtra = 0;
        Empleado e = EmpleadoManager.get();
        
        ArrayList<Trabajo> trabajos 
                = EmpleadoManager.getTrabajos(e.getNumero());
        
        for (Trabajo t : trabajos) {
            Date fecha = t.getFecha();
            if (fecha.before(new Date()) && fecha.after(new Date(2022, 1, 31)))
                sExtra += t.getValor();  
        }
        
        // Actualizamos el objeto (aunque esto se hace solo al hacer el update).
        e.setSueldoExtra(sExtra);
        
        // Actualizamos los datos en la BD
        EmpleadoManager.update("sueldoExtra = " + String.valueOf(sExtra),
                "where numero = " + e.getNumero());
        
        // Actualizamos los datos
        empleadosPane.sueldoExtra.setText(String.valueOf(sExtra));
    }//GEN-LAST:event_calcularSueldoExtraActionPerformed

    private void calcularSueldoRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularSueldoRealActionPerformed
        // Calcular el sueldo real
        calcularSueldoExtraActionPerformed(evt);
        Empleado e = EmpleadoManager.get();
        
        // Usamos el método set para actualizar el sueldo real.
        float sReal = e.getSueldoBase() + Float.parseFloat(sueldoExtra.getText());
        e.setSueldoReal(sReal);

        // Actualizamos los datos en la BD
        EmpleadoManager.update("sueldoReal = " + sueldoExtra.getText(),
                "where numero = " + e.getNumero());

        // Actualizamos los datos
        empleadosPane.sueldoReal.setText(String.valueOf(e.getSueldoReal()));
    }//GEN-LAST:event_calcularSueldoRealActionPerformed

    private void toggleForward(boolean b) {
        // Método interruptor para activar y desactivar los botones para avanzar
        lastButton.setEnabled(b);
        nextButton.setEnabled(b);
    }

    private void toggleBackward(boolean b) {
        // Método interruptor para activar y desactivar los botones para retroceder
        firstButton.setEnabled(b);
        prevButton.setEnabled(b);
    }
    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidosEmp;
    private javax.swing.JLabel apellidosEmpLabel;
    private javax.swing.JButton calcularSueldoExtra;
    private javax.swing.JButton calcularSueldoReal;
    private javax.swing.JLabel empleadosTitle;
    private javax.swing.JButton firstButton;
    private javax.swing.JLabel image;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton lastButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel nombreEmp;
    private javax.swing.JLabel nombreEmpLabel;
    private javax.swing.JLabel numeroEmp;
    private javax.swing.JLabel numeroEmpLabel;
    private javax.swing.JButton prevButton;
    private javax.swing.JLabel sueldoBase;
    private javax.swing.JLabel sueldoBaseLabel;
    private javax.swing.JLabel sueldoExtra;
    private javax.swing.JLabel sueldoExtraLabel;
    private javax.swing.JLabel sueldoMax;
    private javax.swing.JLabel sueldoReal;
    private javax.swing.JLabel sueldoRealLabel;
    private javax.swing.JLabel sueldosLabel;
    private javax.swing.JList<String> trabajosList;
    private javax.swing.JLabel trabajosTitle;
    private javax.swing.JButton verTrabajos;
    // End of variables declaration//GEN-END:variables
}
