/* Ejercicio 1:
Se desea anotar en la tabla auditoria cualquier hecho ocurrido
(insertar, borrar o modificar) y el número de filas afectadas sobre
la tabla emple. (Ej: "Se han borrado 5 filas")
Resolver utilizando Triggers y Paquetes.
*/

/* Ejercicio 2:
Se quiere conseguir la siguiente funcionalidad:
Al borrar un empleado, el campo dir se pondrá igual a nulo en todos
los empleados que dependan de él.
Resolver utilizando Triggers y Paquetes.
*/

/* Ejercicio 3:
Retomamos los ejercicios 2 y 3 del boletin 4. Cargamos los dos y
modificamos el código del departamento 10. Su nuevo valor será 11.
Resolver utilizando Triggers y Paquetes.
*/

/* Ejercicio 4:
Añadir un campo nuevo a la tabla depart llamado media_salario que
almacene la media de salarios de cada departamento.
Se quiere que se actualice su valor al insertar, borrar y modificar
la tabla emple. Resolver utilizando Triggers y Paquetes.
*/