package BernalNavarreteDavid.Vista;

import BernalNavarreteDavid.Controlador.*;
import BernalNavarreteDavid.Modelo.*;
import java.awt.BorderLayout;

public class GUI extends javax.swing.JFrame {

    private Nodo actual;
    private Lista listaEmpleados = new Lista();
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        
        // Fijos: new Fijo(nombre, sueldo máximo, horas al mes, departamento, fecha alta)
        listaEmpleados.añadirNodo(new Nodo(new Fijo("Sacramento Mayo", 2000, 160, "RRHH", "02/02/2020")));
        listaEmpleados.añadirNodo(new Nodo(new Fijo("Brigida Alvarado", 2000, 170, "Admisiones", "19/06/2021")));
        // Temporales: new Temporal(nombre, horas trabajadas, euros hora, sueldo máximo, fecha alta)
        listaEmpleados.añadirNodo(new Nodo(new Temporal("Federico Becerra", 205, 5.6f, 1800, "02/07/2021")));
        listaEmpleados.añadirNodo(new Nodo(new Temporal("Carolina Morán", 178, 6.2f, 1800, "02/02/2019")));
        // Inicializamos el actual.
        actual = listaEmpleados.primero();
        
        initComponents();
        paneDatos.show(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBienvenida = new javax.swing.JPanel();
        labelVersion = new javax.swing.JLabel();
        labelAutor = new javax.swing.JLabel();
        labelBienvenida = new javax.swing.JLabel();
        paneAcciones = new javax.swing.JPanel();
        buttonCancelar = new javax.swing.JButton();
        buttonAceptar = new javax.swing.JButton();
        paneTextfieldsAlta = new javax.swing.JPanel();
        tfieldMaxSalarioAlta = new javax.swing.JTextField();
        tfieldNombreAlta = new javax.swing.JTextField();
        cboxTipoEmpleadoAlta = new javax.swing.JComboBox<>();
        paneFijo = new javax.swing.JPanel();
        paneAtributosFijo = new javax.swing.JPanel();
        labelDepartamento = new javax.swing.JLabel();
        labelHorasMes = new javax.swing.JLabel();
        paneTFFijo = new javax.swing.JPanel();
        tfieldHorasMes = new javax.swing.JTextField();
        tfieldDepartamento = new javax.swing.JTextField();
        paneDatos = new javax.swing.JPanel();
        paneTextfieldsListado = new javax.swing.JPanel();
        tfieldMaxSalarioListado = new javax.swing.JTextField();
        tfieldNombreListado = new javax.swing.JTextField();
        tfieldTipoEmpleadoListado = new javax.swing.JTextField();
        paneTemporal = new javax.swing.JPanel();
        paneAtributosTemporal = new javax.swing.JPanel();
        labelHorasTrabajadas = new javax.swing.JLabel();
        labelEurosHora = new javax.swing.JLabel();
        paneTFTemporal = new javax.swing.JPanel();
        tfieldEurosHora = new javax.swing.JTextField();
        tfieldhorasTrabajadas = new javax.swing.JTextField();
        paneMovimiento = new javax.swing.JPanel();
        buttonAtras = new javax.swing.JButton();
        buttonSiguiente = new javax.swing.JButton();
        paneAtributos = new javax.swing.JPanel();
        labelTipoEmpleados = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelMaxSalario = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuAcciones = new javax.swing.JMenu();
        mItemAlta = new javax.swing.JMenuItem();
        javax.swing.JMenuItem mItemListado = new javax.swing.JMenuItem();
        menuVersion = new javax.swing.JMenu();
        mItemVersion = new javax.swing.JMenuItem();

        labelVersion.setText("Versión 1.0 - 04/10/2021");

        labelAutor.setText("David Bernal Navarrete");

        labelBienvenida.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        labelBienvenida.setText("Listado de Empleados");

        javax.swing.GroupLayout paneBienvenidaLayout = new javax.swing.GroupLayout(paneBienvenida);
        paneBienvenida.setLayout(paneBienvenidaLayout);
        paneBienvenidaLayout.setHorizontalGroup(
            paneBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBienvenidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(paneBienvenidaLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(labelBienvenida)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        paneBienvenidaLayout.setVerticalGroup(
            paneBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBienvenidaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(labelAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVersion)
                .addContainerGap())
        );

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonAceptar.setText("Aceptar");
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneAccionesLayout = new javax.swing.GroupLayout(paneAcciones);
        paneAcciones.setLayout(paneAccionesLayout);
        paneAccionesLayout.setHorizontalGroup(
            paneAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(buttonAceptar)
                .addContainerGap())
        );
        paneAccionesLayout.setVerticalGroup(
            paneAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAccionesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(paneAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonAceptar))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        /**
        * Este panel se muestra cuando se selecciona el alta de Empleado.
        * Contiene los dos TextFields y un ComboBox para la entrada de datos.
        * Sustituye a paneDatos > paneTextfieldsListado.
        */

        tfieldMaxSalarioAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldMaxSalarioAltaActionPerformed(evt);
            }
        });

        tfieldNombreAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldNombreAltaActionPerformed(evt);
            }
        });

        cboxTipoEmpleadoAlta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoEmpleadoAlta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temporal", "Fijo" }));

        javax.swing.GroupLayout paneTextfieldsAltaLayout = new javax.swing.GroupLayout(paneTextfieldsAlta);
        paneTextfieldsAlta.setLayout(paneTextfieldsAltaLayout);
        paneTextfieldsAltaLayout.setHorizontalGroup(
            paneTextfieldsAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTextfieldsAltaLayout.createSequentialGroup()
                .addGroup(paneTextfieldsAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfieldMaxSalarioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxTipoEmpleadoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneTextfieldsAltaLayout.setVerticalGroup(
            paneTextfieldsAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTextfieldsAltaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cboxTipoEmpleadoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfieldNombreAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfieldMaxSalarioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        paneFijo.setLayout(new java.awt.BorderLayout(20, 20));

        labelDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDepartamento.setText("Departamento:");

        labelHorasMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelHorasMes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHorasMes.setText("Horas al mes:");

        javax.swing.GroupLayout paneAtributosFijoLayout = new javax.swing.GroupLayout(paneAtributosFijo);
        paneAtributosFijo.setLayout(paneAtributosFijoLayout);
        paneAtributosFijoLayout.setHorizontalGroup(
            paneAtributosFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosFijoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(paneAtributosFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHorasMes)
                    .addComponent(labelDepartamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneAtributosFijoLayout.setVerticalGroup(
            paneAtributosFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosFijoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHorasMes)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        paneFijo.add(paneAtributosFijo, java.awt.BorderLayout.WEST);

        tfieldHorasMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldHorasMesActionPerformed(evt);
            }
        });

        tfieldDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneTFFijoLayout = new javax.swing.GroupLayout(paneTFFijo);
        paneTFFijo.setLayout(paneTFFijoLayout);
        paneTFFijoLayout.setHorizontalGroup(
            paneTFFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTFFijoLayout.createSequentialGroup()
                .addGroup(paneTFFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfieldHorasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneTFFijoLayout.setVerticalGroup(
            paneTFFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTFFijoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfieldDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfieldHorasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneFijo.add(paneTFFijo, java.awt.BorderLayout.LINE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos de Empleados");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        paneDatos.setLayout(new java.awt.BorderLayout(20, 20));

        tfieldMaxSalarioListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldMaxSalarioListadoActionPerformed(evt);
            }
        });

        tfieldNombreListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldNombreListadoActionPerformed(evt);
            }
        });

        tfieldTipoEmpleadoListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldTipoEmpleadoListadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneTextfieldsListadoLayout = new javax.swing.GroupLayout(paneTextfieldsListado);
        paneTextfieldsListado.setLayout(paneTextfieldsListadoLayout);
        paneTextfieldsListadoLayout.setHorizontalGroup(
            paneTextfieldsListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTextfieldsListadoLayout.createSequentialGroup()
                .addGroup(paneTextfieldsListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfieldMaxSalarioListado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldNombreListado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldTipoEmpleadoListado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneTextfieldsListadoLayout.setVerticalGroup(
            paneTextfieldsListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTextfieldsListadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tfieldTipoEmpleadoListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfieldNombreListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfieldMaxSalarioListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDatos.add(paneTextfieldsListado, java.awt.BorderLayout.EAST);

        paneTemporal.setLayout(new java.awt.BorderLayout());

        labelHorasTrabajadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelHorasTrabajadas.setText("Horas trabajadas:");

        labelEurosHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEurosHora.setText("Euros por hora (€/h):");

        javax.swing.GroupLayout paneAtributosTemporalLayout = new javax.swing.GroupLayout(paneAtributosTemporal);
        paneAtributosTemporal.setLayout(paneAtributosTemporalLayout);
        paneAtributosTemporalLayout.setHorizontalGroup(
            paneAtributosTemporalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosTemporalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelHorasTrabajadas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAtributosTemporalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEurosHora)
                .addContainerGap())
        );
        paneAtributosTemporalLayout.setVerticalGroup(
            paneAtributosTemporalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosTemporalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHorasTrabajadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEurosHora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneTemporal.add(paneAtributosTemporal, java.awt.BorderLayout.WEST);

        tfieldEurosHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldEurosHoraActionPerformed(evt);
            }
        });

        tfieldhorasTrabajadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldhorasTrabajadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneTFTemporalLayout = new javax.swing.GroupLayout(paneTFTemporal);
        paneTFTemporal.setLayout(paneTFTemporalLayout);
        paneTFTemporalLayout.setHorizontalGroup(
            paneTFTemporalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTFTemporalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(paneTFTemporalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfieldhorasTrabajadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldEurosHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        paneTFTemporalLayout.setVerticalGroup(
            paneTFTemporalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTFTemporalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfieldhorasTrabajadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfieldEurosHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneTemporal.add(paneTFTemporal, java.awt.BorderLayout.EAST);

        buttonAtras.setText("Atrás");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });

        buttonSiguiente.setText("Siguiente");
        buttonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneMovimientoLayout = new javax.swing.GroupLayout(paneMovimiento);
        paneMovimiento.setLayout(paneMovimientoLayout);
        paneMovimientoLayout.setHorizontalGroup(
            paneMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMovimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSiguiente)
                .addContainerGap())
        );
        paneMovimientoLayout.setVerticalGroup(
            paneMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMovimientoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(paneMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAtras)
                    .addComponent(buttonSiguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneTemporal.add(paneMovimiento, java.awt.BorderLayout.PAGE_END);

        paneDatos.add(paneTemporal, java.awt.BorderLayout.SOUTH);

        labelTipoEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTipoEmpleados.setText("Tipo de empleado: ");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombre.setText("Nombre:");

        labelMaxSalario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMaxSalario.setText("Salario máximo (€):");

        javax.swing.GroupLayout paneAtributosLayout = new javax.swing.GroupLayout(paneAtributos);
        paneAtributos.setLayout(paneAtributosLayout);
        paneAtributosLayout.setHorizontalGroup(
            paneAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(paneAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMaxSalario)
                    .addComponent(labelNombre)
                    .addComponent(labelTipoEmpleados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneAtributosLayout.setVerticalGroup(
            paneAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelTipoEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMaxSalario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDatos.add(paneAtributos, java.awt.BorderLayout.WEST);

        menuAcciones.setText("Acciones");

        mItemAlta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemAlta.setText("Alta de empleado");
        mItemAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAltaActionPerformed(evt);
            }
        });
        menuAcciones.add(mItemAlta);

        mItemListado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemListado.setText("Listado de empleados");
        mItemListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemListadoActionPerformed(evt);
            }
        });
        menuAcciones.add(mItemListado);

        menuBar.add(menuAcciones);

        menuVersion.setText("Versión");

        mItemVersion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        mItemVersion.setText("Versión 1.0");
        mItemVersion.setEnabled(false);
        mItemVersion.setVerifyInputWhenFocusTarget(false);
        menuVersion.add(mItemVersion);

        menuBar.add(menuVersion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(paneDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemAltaActionPerformed

    private void tfieldMaxSalarioListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldMaxSalarioListadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldMaxSalarioListadoActionPerformed

    private void tfieldNombreListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldNombreListadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldNombreListadoActionPerformed

    private void tfieldHorasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldHorasMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldHorasMesActionPerformed

    private void tfieldDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldDepartamentoActionPerformed

    private void tfieldEurosHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldEurosHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldEurosHoraActionPerformed

    private void tfieldhorasTrabajadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldhorasTrabajadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldhorasTrabajadasActionPerformed

    private void tfieldTipoEmpleadoListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldTipoEmpleadoListadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldTipoEmpleadoListadoActionPerformed

    private void tfieldMaxSalarioAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldMaxSalarioAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldMaxSalarioAltaActionPerformed

    private void tfieldNombreAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldNombreAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldNombreAltaActionPerformed

    private void mItemListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemListadoActionPerformed
        /**
         * Al hacer clic en mostrar el listado, tenemos que:
         * -Quitar los paneles que hubiera antes.
         * -Mostrar el panel de Datos.
         * -Mostrar los datos correspondientes al empleado al actual.
         */
        paneBienvenida.show(false);
        
        paneDatos.show(true);
        paneDatos.remove(paneTextfieldsAlta);
        
        // Desactivamos
        
        // Usamos instanceof para separar entre temporales y fijos.
        if (actual.getObjeto() instanceof Temporal) {
            // Quitamos el panel de Fijos y ponemos el de Temporales
            paneDatos.remove(paneFijo);
            paneDatos.add(paneTemporal, BorderLayout.SOUTH);
            
            // Mostramos los datos del primer elemento.
            //tfieldNombreListado.setText(t);
        }
        else if (actual.getObjeto() instanceof Fijo) {
            // Quitamos el panel de Temporales y colocamos el de Fijos.
            paneDatos.remove(paneTemporal);
            paneDatos.add(paneFijo, BorderLayout.SOUTH);
            
            
        }
        
    }//GEN-LAST:event_mItemListadoActionPerformed

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAtrasActionPerformed

    private void buttonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSiguienteActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JButton buttonAtras;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSiguiente;
    private javax.swing.JComboBox<String> cboxTipoEmpleadoAlta;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JLabel labelDepartamento;
    private javax.swing.JLabel labelEurosHora;
    private javax.swing.JLabel labelHorasMes;
    private javax.swing.JLabel labelHorasTrabajadas;
    private javax.swing.JLabel labelMaxSalario;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTipoEmpleados;
    private javax.swing.JLabel labelVersion;
    private javax.swing.JMenuItem mItemAlta;
    private javax.swing.JMenuItem mItemVersion;
    private javax.swing.JMenu menuAcciones;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuVersion;
    private javax.swing.JPanel paneAcciones;
    private javax.swing.JPanel paneAtributos;
    private javax.swing.JPanel paneAtributosFijo;
    private javax.swing.JPanel paneAtributosTemporal;
    private javax.swing.JPanel paneBienvenida;
    private javax.swing.JPanel paneDatos;
    private javax.swing.JPanel paneFijo;
    private javax.swing.JPanel paneMovimiento;
    private javax.swing.JPanel paneTFFijo;
    private javax.swing.JPanel paneTFTemporal;
    private javax.swing.JPanel paneTemporal;
    private javax.swing.JPanel paneTextfieldsAlta;
    private javax.swing.JPanel paneTextfieldsListado;
    private javax.swing.JTextField tfieldDepartamento;
    private javax.swing.JTextField tfieldEurosHora;
    private javax.swing.JTextField tfieldHorasMes;
    private javax.swing.JTextField tfieldMaxSalarioAlta;
    private javax.swing.JTextField tfieldMaxSalarioListado;
    private javax.swing.JTextField tfieldNombreAlta;
    private javax.swing.JTextField tfieldNombreListado;
    private javax.swing.JTextField tfieldTipoEmpleadoListado;
    private javax.swing.JTextField tfieldhorasTrabajadas;
    // End of variables declaration//GEN-END:variables
}
