/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.GestorNavegador;
import Modelo.Cuenta;

/**
 *
 * @author alumno
 */
public class Cuentas extends javax.swing.JPanel {

    private static void mostrar(Cuenta c) {
        numCuentaF.setText(String.valueOf(c.getNumero()));
        fechaF.setText(c.getFecha().toString());
        saldoF.setText(String.valueOf(c.getSaldo()));
        saldoMinF.setText(String.valueOf(c.getSaldoMin()));
        interesF.setText(String.valueOf(c.getInteres()));
        
        if (GestorNavegador.esPrimero()){
            primeraB.setEnabled(false);
            anteriorB.setEnabled(false);
        } else if (GestorNavegador.esUltimo()) {
            ultimaB.setEnabled(false);
            siguienteB.setEnabled(false);
        }
    }
    
    /**
     * Creates new form Cuentas
     */
    public Cuentas() {
        initComponents();
    }
    
    public static void start(int codCli) {
        GestorNavegador.iniciar(codCli);
        mostrar(GestorNavegador.leer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siguienteB = new javax.swing.JButton();
        anteriorB = new javax.swing.JButton();
        ultimaB = new javax.swing.JButton();
        primeraB = new javax.swing.JButton();
        calcularInteresesB = new javax.swing.JButton();
        movimientosB = new javax.swing.JButton();
        numCuentaL = new javax.swing.JLabel();
        fechaL = new javax.swing.JLabel();
        saldoL = new javax.swing.JLabel();
        saldoMinL = new javax.swing.JLabel();
        interesL = new javax.swing.JLabel();
        numCuentaF = new javax.swing.JLabel();
        fechaF = new javax.swing.JLabel();
        saldoF = new javax.swing.JLabel();
        saldoMinF = new javax.swing.JLabel();
        interesF = new javax.swing.JLabel();

        siguienteB.setText("Siguiente");
        siguienteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBActionPerformed(evt);
            }
        });

        anteriorB.setText("Anterior");
        anteriorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorBActionPerformed(evt);
            }
        });

        ultimaB.setText("Última");
        ultimaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimaBActionPerformed(evt);
            }
        });

        primeraB.setText("Primera");
        primeraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeraBActionPerformed(evt);
            }
        });

        calcularInteresesB.setText("Calcular Intereses");
        calcularInteresesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularInteresesBActionPerformed(evt);
            }
        });

        movimientosB.setText("Movimientos");
        movimientosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movimientosBActionPerformed(evt);
            }
        });

        numCuentaL.setText("Número de cuenta:");

        fechaL.setText("Fecha:");

        saldoL.setText("Saldo");

        saldoMinL.setText("Saldo Mínimo:");

        interesL.setText("Interés:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(primeraB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anteriorB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siguienteB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ultimaB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calcularInteresesB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(movimientosB)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(interesL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(interesF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saldoMinL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saldoMinF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saldoL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saldoF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numCuentaL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numCuentaF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCuentaL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numCuentaF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoMinL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoMinF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interesL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interesF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularInteresesB)
                    .addComponent(movimientosB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguienteB)
                    .addComponent(anteriorB)
                    .addComponent(ultimaB)
                    .addComponent(primeraB))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBActionPerformed
        if (!anteriorB.isEnabled()) {
            anteriorB.setEnabled(true);
            primeraB.setEnabled(true);
        }
        
        GestorNavegador.avanzar();
        mostrar(GestorNavegador.leer());
    }//GEN-LAST:event_siguienteBActionPerformed

    private void anteriorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorBActionPerformed
        if (!siguienteB.isEnabled()) {
            siguienteB.setEnabled(true);
            ultimaB.setEnabled(true);
        }
        
        GestorNavegador.retroceder();
        mostrar(GestorNavegador.leer());
    }//GEN-LAST:event_anteriorBActionPerformed

    private void primeraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeraBActionPerformed
        if (!siguienteB.isEnabled()) {
            siguienteB.setEnabled(true);
            ultimaB.setEnabled(true);
        }
        
        GestorNavegador.primero();
        mostrar(GestorNavegador.leer());
    }//GEN-LAST:event_primeraBActionPerformed

    private void ultimaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimaBActionPerformed
         if (!anteriorB.isEnabled()) {
            anteriorB.setEnabled(true);
            primeraB.setEnabled(true);
        }
        
        GestorNavegador.ultimo();
        mostrar(GestorNavegador.leer());
    }//GEN-LAST:event_ultimaBActionPerformed

    private void calcularInteresesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularInteresesBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularInteresesBActionPerformed

    private void movimientosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimientosBActionPerformed
        MainFrame mf = MainFrame.getMainFrame();
        mf.cambiarPanel(MainFrame.getMovimientos());
    }//GEN-LAST:event_movimientosBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton anteriorB;
    private static javax.swing.JButton calcularInteresesB;
    private static javax.swing.JLabel fechaF;
    private javax.swing.JLabel fechaL;
    private static javax.swing.JLabel interesF;
    private javax.swing.JLabel interesL;
    private static javax.swing.JButton movimientosB;
    private static javax.swing.JLabel numCuentaF;
    private javax.swing.JLabel numCuentaL;
    private static javax.swing.JButton primeraB;
    private static javax.swing.JLabel saldoF;
    private javax.swing.JLabel saldoL;
    private static javax.swing.JLabel saldoMinF;
    private javax.swing.JLabel saldoMinL;
    private static javax.swing.JButton siguienteB;
    private static javax.swing.JButton ultimaB;
    // End of variables declaration//GEN-END:variables
}
