/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.GestorValidacion;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public final class MainFrame extends javax.swing.JFrame {
    
    private static final MainFrame mainf = new MainFrame();
    private static Cuentas cuentas;
    private static InfoAlumno infoAlum;
    private static InfoCliente infoCli;
    private static Movimientos movimientos;
    private static Validacion validacion;  
    private static boolean acceso = false;


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        cuentas = new Cuentas();
        infoAlum = new InfoAlumno();
        infoCli = new InfoCliente();
        movimientos = new Movimientos();
        validacion = new Validacion();
        
        this.setContentPane(validacion);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        usuarioMenu = new javax.swing.JMenu();
        datosUsuarioMItem = new javax.swing.JMenuItem();
        cuentasUsuarioMItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cerrarSesionMItem = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("David Bernal Navarrete");
        setResizable(false);

        usuarioMenu.setText("Usuario");
        usuarioMenu.setEnabled(false);

        datosUsuarioMItem.setText("Mis datos");
        datosUsuarioMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosUsuarioMItemActionPerformed(evt);
            }
        });
        usuarioMenu.add(datosUsuarioMItem);

        cuentasUsuarioMItem.setText("Mis cuentas");
        cuentasUsuarioMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentasUsuarioMItemActionPerformed(evt);
            }
        });
        usuarioMenu.add(cuentasUsuarioMItem);
        usuarioMenu.add(jSeparator2);

        cerrarSesionMItem.setText("Cerrar sesión...");
        cerrarSesionMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionMItemActionPerformed(evt);
            }
        });
        usuarioMenu.add(cerrarSesionMItem);

        jMenuBar1.add(usuarioMenu);

        ayudaMenu.setText("Ayuda");
        ayudaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayudaMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(ayudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ayudaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaMenuMouseClicked
        cambiarPanel(infoAlum);
    }//GEN-LAST:event_ayudaMenuMouseClicked

    private void cerrarSesionMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionMItemActionPerformed
        this.usuarioMenu.setEnabled(false);
        cambiarPanel(validacion);
    }//GEN-LAST:event_cerrarSesionMItemActionPerformed

    private void cuentasUsuarioMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentasUsuarioMItemActionPerformed
        Cuentas.start(GestorValidacion.getCliente().getCod());
        cambiarPanel(cuentas);
    }//GEN-LAST:event_cuentasUsuarioMItemActionPerformed

    private void datosUsuarioMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosUsuarioMItemActionPerformed
        InfoCliente.start();
        cambiarPanel(infoCli);
    }//GEN-LAST:event_datosUsuarioMItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                mainf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JMenuItem cerrarSesionMItem;
    private javax.swing.JMenuItem cuentasUsuarioMItem;
    private javax.swing.JMenuItem datosUsuarioMItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu usuarioMenu;
    // End of variables declaration//GEN-END:variables

    
    public static InfoCliente getInfoCli() {
        return MainFrame.infoCli;
    }
    
    public static Movimientos getMovimientos() {
        return MainFrame.movimientos;
    }
    
    public static Cuentas getCuentas() {
        return MainFrame.cuentas;
    }
    
    public static Validacion getValidacion() {
        return MainFrame.validacion;
    }
    
    public static MainFrame getMainFrame() {
        return MainFrame.mainf;
    }
    
    public void cambiarPanel(JPanel panel) {
        mainf.setContentPane(panel);
        mainf.pack();
    }
    
    public void setAcceso(boolean b) {
        MainFrame.acceso = b;
        if (b) {
            usuarioMenu.setEnabled(true);
            InfoCliente.start();
        }
        else 
            usuarioMenu.setEnabled(false);
    }
    
    public static boolean getAcceso() {
        return acceso;
    }
}
