/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JPanel;

/**
 *
 * @author David
 * TO-DO:
 * -Menú bar para moverse entre los paneles de forma directa (desactivado si no
 * se ha iniciado sesión). En la barra el botón "About" siempre está activo, y el
 * botón "Login" solo se muestra si no se ha iniciado sesión.
 * -Añadir Login como el panel principal.
 * -Crear variables para todos los paneles.
 * -Crear métodos para obtener los paneles y poder cambiar entre ellos, desde 
 * ellos.
 */
public class MainFrame extends javax.swing.JFrame {
    // Variables para los paneles:
    private final static MainFrame mainFrame = new MainFrame();
    private static Login loginPanel;
    private static About aboutPanel;
    private static NewTransaction newTransactionPanel;
    private static Orders ordersPanel;
    private static Profile profilePanel;
    private boolean userAccess = false;
    

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        loginPanel = new Login();
        aboutPanel = new About();
        newTransactionPanel = new NewTransaction();
        ordersPanel = new Orders();
        profilePanel = new Profile ();
        
        // Desactivar botones que no se usan hasta estar logeado.
        this.login.setEnabled(false);
        this.newTransaction.setEnabled(false);
        this.orders.setEnabled(false);
        this.profile.setEnabled(false);
        
        // Mostrar el panel de Login.
        this.setContentPane(loginPanel);
        this.pack();
    }
    
    // <editor-fold defaultstate="collapsed" desc="Métodos para cambiar paneles"> 
    public void changePanel(JPanel panel) {
        mainFrame.setContentPane(panel);
        mainFrame.pack();
    }

    public static MainFrame getMainFrame() {
        return mainFrame;
    }

    public static Login getLoginPanel() {
        return loginPanel;
    }

    public static About getAboutPanel() {
        return aboutPanel;
    }

    public static NewTransaction getNewTransactionPanel() {
        return newTransactionPanel;
    }

    public static Orders getOrdersPanel() {
        return ordersPanel;
    }

    public static Profile getProfilePanel() {
        return profilePanel;
    }
    
    public static void changeUserAccess(boolean b) {
        mainFrame.setUserAccess(b);
    }
    
    public void setUserAccess(boolean b) {
        if (b) {
            this.login.setEnabled(false);
            this.profile.setEnabled(false);
            this.orders.setEnabled(true);
            this.newTransaction.setEnabled(true);
        } else {
            this.profile.setEnabled(false);
            this.orders.setEnabled(false);
            this.newTransaction.setEnabled(false);
            changePanel(this.loginPanel);
        }
        this.userAccess = b;
    }
    // </editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        login = new javax.swing.JMenu();
        profile = new javax.swing.JMenu();
        closeSession = new javax.swing.JMenuItem();
        orders = new javax.swing.JMenu();
        newTransaction = new javax.swing.JMenu();
        about = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        menuBar.add(login);

        profile.setText("My Profile");

        closeSession.setText("Close Session");
        profile.add(closeSession);

        menuBar.add(profile);

        orders.setText("Orders");
        menuBar.add(orders);

        newTransaction.setText("New Transaction");
        menuBar.add(newTransaction);

        about.setText("About");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        menuBar.add(about);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Event Listeners">
    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // Cambia el panel de contenido al panel About.
        changePanel(mainFrame.getAboutPanel());
        this.login.setEnabled(true);
        this.about.setEnabled(false);
    }//GEN-LAST:event_aboutMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // Cambia el panel del MainFrame al panel About.
        changePanel(mainFrame.getLoginPanel());
        this.login.setEnabled(false);
        this.about.setEnabled(true);
    }//GEN-LAST:event_loginMouseClicked

    // </editor-fold>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem closeSession;
    private javax.swing.JMenu login;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu newTransaction;
    private javax.swing.JMenu orders;
    private javax.swing.JMenu profile;
    // End of variables declaration//GEN-END:variables
}
